# -*- coding: utf-8 -*-
"""
TOPAS-like invariant fit (project-integrated)

Input is derived from:
  1) Contrast_Factor/contrast_factors.in  (JSON)
  2) The contrast-factor output file generated by main.py:
        {material_name}_{lattice}_plane[... ]_burgers[... ].txt

Expected output file format (columns):
h k l  delta_deg_phi0  C_eq_avg_phi0  delta_deg_phi90  C_eq_avg_phi90

- delta_* columns are ignored by the fit (kept for reference / plotting)
- C_eq_avg_phi0 is used for SCREW fit
- C_eq_avg_phi90 is used for EDGE fit

Outputs:
  - <OUT_PREFIX>_comparison_screw_TOPAS.csv
  - <OUT_PREFIX>_comparison_edge_TOPAS.csv
  - <OUT_PREFIX>_comparison_screw_PAPER.csv
  - <OUT_PREFIX>_comparison_edge_PAPER.csv

and for multi-phi:
  - <OUT_PREFIX>_comparison_phi{phi}_TOPAS.csv
  - <OUT_PREFIX>_comparison_phi{phi}_PAPER.csv

NOTE (your request):
  - Monoclinic PAPER normalization was removed completely.
  - Tetragonal PAPER (75-88, 89-142) and Cubic PAPER are kept.
  - For monoclinic SG 3..15, PAPER mode now falls back to TOPAS direction-cosines.
"""

from __future__ import annotations

import os
import json
import numpy as np
import pandas as pd
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple


# ============================
# CONFIG
# ============================

OUTPUT_DIR = r"./output_fit"
OUT_PREFIX = "fit"

FORCE_SG: int | None = None
FORCE_CELL: tuple[float, float, float, float, float, float] | None = None
FORCE_INPUT_TABLE: str | None = None


# ============================
# Cell + reciprocal handling
# ============================

@dataclass(frozen=True)
class Cell:
    a: float
    b: float
    c: float
    alpha: float = 90.0
    beta: float = 90.0
    gamma: float = 90.0


def _infer_lattice_from_space_group(space_group: int) -> str:
    sg = int(space_group)
    if sg < 1 or sg > 230:
        raise ValueError(f"space_group must be in 1..230, got {space_group}")
    if sg <= 2:
        return "triclinic"
    if sg <= 15:
        return "monoclinic"
    if sg <= 74:
        return "orthorhombic"
    if sg <= 142:
        return "tetragonal"
    if sg <= 167:
        return "trigonal"
    if sg <= 194:
        return "hexagonal"
    return "cubic"


def _cell_from_json_table_driven(data: dict) -> Cell:
    """
    Build a complete Cell using a table-driven convention (matches project rules):

      cubic:        a
      tetragonal:   a, c        => b=a; alpha=beta=gamma=90
      hexagonal:    a, c        => b=a; alpha=beta=90; gamma=120
      trigonal:     a, c (hex setting) => b=a; alpha=beta=90; gamma=120
      orthorhombic: a, b, c     => alpha=beta=gamma=90
      monoclinic:   a, b, c, beta => alpha=gamma=90
      triclinic:    a, b, c, alpha, beta, gamma
    """
    cell_json = data.get("cell", {})
    if not isinstance(cell_json, dict):
        raise ValueError("cell must be an object")

    sg = data.get("space_group", data.get("space_group_number", None))
    lattice_in = cell_json.get("lattice", None)

    lattice = str(lattice_in).lower() if lattice_in is not None else None
    if lattice is None:
        if sg is None:
            raise ValueError("Input must provide either cell.lattice or space_group")
        lattice = _infer_lattice_from_space_group(int(sg))

    def req(name: str) -> float:
        if name not in cell_json:
            raise ValueError(f"cell.{name} is required for lattice='{lattice}'")
        return float(cell_json[name])

    if lattice == "cubic":
        a = req("a")
        return Cell(a=a, b=a, c=a, alpha=90.0, beta=90.0, gamma=90.0)

    if lattice == "tetragonal":
        a = req("a")
        c = req("c")
        return Cell(a=a, b=a, c=c, alpha=90.0, beta=90.0, gamma=90.0)

    if lattice == "hexagonal":
        a = req("a")
        c = req("c")
        return Cell(a=a, b=a, c=c, alpha=90.0, beta=90.0, gamma=120.0)

    if lattice == "trigonal":
        # Default to hexagonal axes setting (a,c) as per your table.
        a = req("a")
        c = req("c")
        return Cell(a=a, b=a, c=c, alpha=90.0, beta=90.0, gamma=120.0)

    if lattice == "orthorhombic":
        a = req("a")
        b = req("b")
        c = req("c")
        return Cell(a=a, b=b, c=c, alpha=90.0, beta=90.0, gamma=90.0)

    if lattice == "monoclinic":
        a = req("a")
        b = req("b")
        c = req("c")
        beta = req("beta")
        return Cell(a=a, b=b, c=c, alpha=90.0, beta=beta, gamma=90.0)

    if lattice == "triclinic":
        a = req("a")
        b = req("b")
        c = req("c")
        alpha = req("alpha")
        beta = req("beta")
        gamma = req("gamma")
        return Cell(a=a, b=b, c=c, alpha=alpha, beta=beta, gamma=gamma)

    raise ValueError(f"Unsupported lattice='{lattice}'")


def _deg2rad(x: float) -> float:
    return np.deg2rad(x)


def _is_close(x: float, y: float, tol: float = 1e-6) -> bool:
    return abs(x - y) <= tol


def reciprocal_params(cell: Cell):
    a, b, c = cell.a, cell.b, cell.c
    al, be, ga = map(_deg2rad, (cell.alpha, cell.beta, cell.gamma))

    ca, cb, cg = np.cos(al), np.cos(be), np.cos(ga)
    sa, sb, sg = np.sin(al), np.sin(be), np.sin(ga)

    V = a * b * c * np.sqrt(1.0 + 2.0 * ca * cb * cg - ca**2 - cb**2 - cg**2)

    astar = (b * c * sa) / V
    bstar = (a * c * sb) / V
    cstar = (a * b * sg) / V

    cos_al_star = (cb * cg - ca) / (sb * sg)
    cos_be_star = (ca * cg - cb) / (sa * sg)
    cos_ga_star = (ca * cb - cg) / (sa * sb)

    cos_al_star = np.clip(cos_al_star, -1.0, 1.0)
    cos_be_star = np.clip(cos_be_star, -1.0, 1.0)
    cos_ga_star = np.clip(cos_ga_star, -1.0, 1.0)

    al_star = np.arccos(cos_al_star)
    be_star = np.arccos(cos_be_star)
    ga_star = np.arccos(cos_ga_star)

    return astar, bstar, cstar, al_star, be_star, ga_star


def _direct_basis_cart(cell: Cell) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Build direct lattice basis vectors a,b,c in Cartesian coordinates.
    Convention:
      a along x
      b in xy plane
      c with general orientation
    """
    a, b, c = cell.a, cell.b, cell.c
    al = np.deg2rad(cell.alpha)
    be = np.deg2rad(cell.beta)
    ga = np.deg2rad(cell.gamma)

    ax = np.array([a, 0.0, 0.0], dtype=float)
    bx = np.array([b * np.cos(ga), b * np.sin(ga), 0.0], dtype=float)

    cx_x = c * np.cos(be)
    cx_y = c * (np.cos(al) - np.cos(be) * np.cos(ga)) / np.sin(ga)
    cx_z_sq = c**2 - cx_x**2 - cx_y**2
    cx_z = np.sqrt(max(cx_z_sq, 0.0))
    cx = np.array([cx_x, cx_y, cx_z], dtype=float)

    return ax, bx, cx


def _reciprocal_basis_cart(cell: Cell) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Reciprocal basis vectors a*, b*, c* in Cartesian coordinates (2π omitted).
    """
    a, b, c = _direct_basis_cart(cell)
    V = np.dot(a, np.cross(b, c))
    if abs(V) < 1e-18:
        raise ValueError("Cell volume is zero or numerically unstable.")

    astar = np.cross(b, c) / V
    bstar = np.cross(c, a) / V
    cstar = np.cross(a, b) / V
    return astar, bstar, cstar


def d_spacing(cell: Cell, h: int, k: int, l: int) -> float:
    """
    d(hkl) using the same geometry already used in HKL_direction_cosines():
      g = h a* + k b* + l c*   (2π omitted)
      |g| = 1/d
    """
    astar, bstar, cstar = _reciprocal_basis_cart(cell)
    g = h * astar + k * bstar + l * cstar
    gnorm = float(np.linalg.norm(g))
    if gnorm <= 0.0:
        raise ValueError(f"Non-positive |g| for hkl=({h},{k},{l}).")
    return 1.0 / gnorm


def HKL_direction_cosines(h: int, k: int, l: int, cell: Cell) -> Tuple[float, float, float]:
    """
    True direction cosines of g = h a* + k b* + l c* with respect to the
    reciprocal basis directions (unit vectors along a*, b*, c*), computed in Cartesian space.
    """
    astar, bstar, cstar = _reciprocal_basis_cart(cell)

    g = h * astar + k * bstar + l * cstar
    gnorm = float(np.linalg.norm(g))
    if gnorm <= 0.0:
        raise ValueError(f"Non-positive |g| for hkl=({h},{k},{l}).")

    ea = astar / np.linalg.norm(astar)
    eb = bstar / np.linalg.norm(bstar)
    ec = cstar / np.linalg.norm(cstar)

    H = float(np.dot(g, ea) / gnorm)
    K = float(np.dot(g, eb) / gnorm)
    L = float(np.dot(g, ec) / gnorm)
    return H, K, L


# ============================
# TOPAS macro -> feature vector
# ============================

def required_terms_for_sg(sg: int, cell: Cell) -> List[str]:
    if sg in (1, 2):
        return [f"E{i}" for i in range(1, 16)]
    if 3 <= sg <= 15:
        if _is_close(cell.alpha, 90.0) and _is_close(cell.gamma, 90.0):
            return [f"E{i}" for i in range(1, 10)]
        if _is_close(cell.alpha, 90.0) and _is_close(cell.beta, 90.0):
            return [f"E{i}" for i in range(1, 10)]
        raise ValueError("Invalid monoclinic cell for TOPAS macro rules.")
    if 16 <= sg <= 74:
        return [f"E{i}" for i in range(1, 7)]
    if 75 <= sg <= 88:
        return [f"E{i}" for i in range(1, 6)]
    if 89 <= sg <= 142:
        return [f"E{i}" for i in range(1, 5)]
    if 143 <= sg <= 148:
        return ["E1", "E2", "E3", "E4", "E5"]
    if 149 <= sg <= 167:
        return ["E1", "E2", "E3", "E4"]
    if 168 <= sg <= 194:
        return ["E1", "E2", "E3"]
    if 195 <= sg <= 230:
        return ["E1", "E2"]
    raise ValueError("Space group out of range (1..230).")


# ----------------------------
# PAPER feature vectors (kept)
# ----------------------------

def feature_vector_cubic_miller_paper(h: int, k: int, l: int, cell: Cell) -> tuple[list[str], np.ndarray]:
    """
    Cubic paper-style:
      Cbar = [E1(h^4+k^4+l^4) + 2E2(h^2k^2+h^2l^2+k^2l^2)] * (d(hkl)^4 / a^4)
    """
    a = float(cell.a)
    d = d_spacing(cell, h, k, l)
    scale = (d**4) / (a**4)

    h2, k2, l2 = h*h, k*k, l*l
    h4, k4, l4 = h2*h2, k2*k2, l2*l2

    names = ["E1", "E2"]
    x = np.array([
        (h4 + k4 + l4) * scale,
        (2.0 * (h2*k2 + h2*l2 + k2*l2)) * scale,
    ], dtype=float)
    return names, x


def feature_vector_tetragonal_75_88_paper(h: int, k: int, l: int, cell: Cell) -> tuple[list[str], np.ndarray]:
    """
    Martinez-Garcia et al. tetragonal 4/m (75..88):
      [E1(h^4+k^4) + E2 l^4 + 2E3 h^2 k^2 + 2E4 l^2(h^2+k^2) + 4E5 h k (h^2-k^2)]
      / [h^2 + k^2 + (a/c)^2 l^2]^2
    """
    a = cell.a
    c = cell.c
    r = (a / c) ** 2

    h2, k2, l2 = h*h, k*k, l*l
    h4, k4, l4 = h2*h2, k2*k2, l2*l2

    denom = (h2 + k2 + r * l2) ** 2

    names = ["E1", "E2", "E3", "E4", "E5"]
    x = np.array([
        (h4 + k4) / denom,
        (l4) / denom,
        (2*h2*k2) / denom,
        (2*l2*(h2 + k2)) / denom,
        (4*h*k*(h2 - k2)) / denom,
    ], dtype=float)
    return names, x


def feature_vector_tetragonal_89_142_paper(h: int, k: int, l: int, cell: Cell) -> tuple[list[str], np.ndarray]:
    a = cell.a
    c = cell.c
    r = (a / c) ** 2

    h2, k2, l2 = h*h, k*k, l*l
    h4, k4, l4 = h2*h2, k2*k2, l2*l2

    denom = (h2 + k2 + r * l2) ** 2

    names = ["E1", "E3", "E4", "E5"]
    x = np.array([
        (h4 + k4) / denom,
        (l4) / denom,
        (2*h2*k2) / denom,
        (2*l2*(h2 + k2)) / denom,
    ], dtype=float)
    return names, x


def feature_vector_tetragonal_paper(h: int, k: int, l: int, cell: Cell) -> tuple[list[str], np.ndarray]:
    """
    Paper definition:
      [E1(h^4+k^4) + E3 l^4 + 2E4 h^2 k^2 + 2E5 l^2(h^2+k^2)] / d^4
    with tetragonal:
      1/d^2 = (h^2+k^2)/a^2 + l^2/c^2
    """
    a = cell.a
    c = cell.c

    h2, k2, l2 = h*h, k*k, l*l
    h4, k4, l4 = h2*h2, k2*k2, l2*l2

    inv_d2 = (h2 + k2) / (a*a) + (l2) / (c*c)
    inv_d4 = inv_d2 * inv_d2

    names = ["E1", "E3", "E4", "E5"]
    x = np.array([
        (h4 + k4) * inv_d4,
        (l4)      * inv_d4,
        (2*h2*k2) * inv_d4,
        (2*l2*(h2 + k2)) * inv_d4,
    ], dtype=float)
    return names, x


# ----------------------------
# TOPAS macro features (H,K,L)
# ----------------------------

def feature_vector(sg: int, H: float, K: float, L: float, cell: Cell) -> Tuple[List[str], np.ndarray]:
    H2, K2, L2 = H * H, K * K, L * L
    H3, K3, L3 = H2 * H, K2 * K, L2 * L
    H4, K4, L4 = H2 * H2, K2 * K2, L2 * L2

    if sg in (1, 2):
        names = [f"E{i}" for i in range(1, 16)]
        x = np.array([
            H4, K4, L4,
            2*(H2*K2), 2*(K2*L2), 2*(H2*L2),
            4*(H3*K), 4*(H3*L), 4*(H*K3), 4*(K3*L),
            4*(H*L3), 4*(K*L3),
            4*(H2*K*L), 4*(H*K2*L), 4*(H*K*L2),
        ], dtype=float)
        return names, x

    if 3 <= sg <= 15:
        if _is_close(cell.alpha, 90.0) and _is_close(cell.gamma, 90.0):
            names = [f"E{i}" for i in range(1, 10)]
            x = np.array([
                H4, K4, L4,
                2*(H2*L2), 2*(K2*L2), 2*(H2*K2),
                4*(H3*L), 4*(H*L3), 4*(H*K2*L),
            ], dtype=float)
            return names, x

        if _is_close(cell.alpha, 90.0) and _is_close(cell.beta, 90.0):
            names = [f"E{i}" for i in range(1, 10)]
            x = np.array([
                H4, K4, L4,
                2*(H2*K2), 2*(K2*L2), 2*(H2*L2),
                4*(H3*K), 4*(H*K3), 4*(H*K*L2),
            ], dtype=float)
            return names, x

        raise ValueError("Invalid monoclinic cell for TOPAS macro rules.")

    if 16 <= sg <= 74:
        names = [f"E{i}" for i in range(1, 7)]
        x = np.array([H4, K4, L4, 2*(H2*K2), 2*(K2*L2), 2*(H2*L2)], dtype=float)
        return names, x

    if 75 <= sg <= 88:
        names = ["E1", "E2", "E3", "E4", "E5"]
        x = np.array([
            (H4 + K4),
            L4,
            2*(H2*K2),
            2*((H2 + K2)*L2),
            4*(H*K*(H2 - K2)),
        ], dtype=float)
        return names, x

    if 89 <= sg <= 142:
        names = ["E1", "E2", "E3", "E4"]
        x = np.array([
            (H4 + K4),
            L4,
            2*(H2*K2),
            2*((H2 + K2)*L2),
        ], dtype=float)
        return names, x

    if 143 <= sg <= 148:
        rhombo_support = {146, 148}
        ga = cell.gamma
        names = ["E1", "E2", "E3", "E4", "E5"]

        if sg in rhombo_support:
            if _is_close(ga, 120.0):
                A = (H2 - H*K + K2)
                x = np.array([A*A, 2*A*L2, L4,
                              4*(H*(H-K)*K*L),
                              4*((H3 - 3*H*K2 + K3)*L)], dtype=float)
                return names, x
            if _is_close(ga, 60.0):
                A = (H2 + H*K + K2)
                x = np.array([A*A, 2*A*L2, L4,
                              (4/3)*L*(H3 + 3*H2*K - K3),
                              (4/3)*L*(-H3 + 3*H*K2 + K3)], dtype=float)
                return names, x

        if _is_close(ga, 120.0):
            A = (H2 - H*K + K2)
            x = np.array([A*A, 2*A*L2, L4,
                          4*(H*(H-K)*K*L),
                          4*((H3 - 3*H*K2 + K3)*L)], dtype=float)
            return names, x

        A = (H2 + H*K + K2)
        x = np.array([A*A, 2*A*L2, L4,
                      (4/3)*L*(H3 + 3*H2*K - K3),
                      (4/3)*L*(-H3 + 3*H*K2 + K3)], dtype=float)
        return names, x

    if 149 <= sg <= 167:
        trig_m1 = {150, 152, 154, 155, 156, 158, 160, 161, 164, 165, 166, 167}
        rhombo_support = {155, 160, 161, 166, 167}
        ga = cell.gamma
        names = ["E1", "E2", "E3", "E4"]

        if sg in trig_m1:
            if sg in rhombo_support:
                if _is_close(ga, 120.0):
                    A = (H2 - H*K + K2)
                    x = np.array([A*A, 2*L2*A, L4, 4*(H*K*L*(H-K))], dtype=float)
                    return names, x
                if _is_close(ga, 60.0):
                    A = (H2 + H*K + K2)
                    x = np.array([A*A, 2*L2*A, L4, 4*(H*K*L*(H+K))], dtype=float)
                    return names, x

            if _is_close(ga, 120.0):
                A = (H2 - H*K + K2)
                x = np.array([A*A, 2*L2*A, L4, 4*(H*K*L*(H-K))], dtype=float)
                return names, x

            A = (H2 + H*K + K2)
            x = np.array([A*A, 2*L2*A, L4, 4*(H*K*L*(H+K))], dtype=float)
            return names, x

        if _is_close(ga, 120.0):
            A = (H2 - H*K + K2)
            x = np.array([A*A, 2*L2*A, L4, L*(4*H3 - 6*H2*K - 6*H*K2 + 4*K3)], dtype=float)
            return names, x

        A = (H2 + H*K + K2)
        x = np.array([A*A, 2*L2*A, L4, (4/3)*L*(2*H3 + 3*H2*K - 3*H*K2 - 2*K3)], dtype=float)
        return names, x

    if 168 <= sg <= 194:
        ga = cell.gamma
        names = ["E1", "E2", "E3"]
        A = (H2 + H*K + K2) if _is_close(ga, 120.0) else (H2 - H*K + K2)
        x = np.array([A*A, 2*L2*A, L4], dtype=float)
        return names, x

    if 195 <= sg <= 230:
        names = ["E1", "E2"]
        x = np.array([(H4 + K4 + L4), 2*(H2*K2 + H2*L2 + K2*L2)], dtype=float)
        return names, x

    raise ValueError("Space group out of range (1..230).")


# ============================
# Input parsing
# ============================

def _default_sg_for_lattice(lattice: str) -> int:
    lat = lattice.lower()
    if lat == "triclinic":
        return 1
    if lat == "monoclinic":
        return 5
    if lat == "orthorhombic":
        return 62
    if lat == "tetragonal":
        return 89
    if lat in ("trigonal", "rhombohedral"):
        return 149
    if lat == "hexagonal":
        return 168
    if lat == "cubic":
        return 225
    raise ValueError(f"Unsupported lattice '{lattice}' for SG default mapping.")


def _output_table_path_from_contrast_in(contrast_in_path: Path) -> Path:
    with contrast_in_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    material_name = str(data.get("material_name", "Material"))

    cellj = data.get("cell", {})
    lattice = str(cellj.get("lattice", "")).lower()

    slip0 = data["slip_systems"][0]
    plane_hkl = slip0["plane_hkl"]
    burgers_uvw = slip0["burgers_uvw"]

    plane_str = "_".join(str(int(x)) for x in plane_hkl)
    burg_str = "_".join(str(int(x)) for x in burgers_uvw)

    out_name = f"{material_name}_{lattice}_plane[{plane_str}]_burgers[{burg_str}].txt"
    return (contrast_in_path.parent / out_name).resolve()


def _load_cell_from_contrast_in(data: dict) -> Cell:
    # Use table-driven symmetry constraints (so hexagonal a,c implies gamma=120, b=a, ...)
    return _cell_from_json_table_driven(data)


def parse_project_table(path: str) -> pd.DataFrame:
    rows: list[tuple[int, int, int, float, float, float, float]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            raw = line.strip()
            if not raw or raw.startswith("#"):
                continue
            parts = raw.split()
            if len(parts) < 7:
                continue
            h, k, l = map(int, parts[0:3])
            delta0 = float(parts[3])
            c0 = float(parts[4])
            delta90 = float(parts[5])
            c90 = float(parts[6])
            rows.append((h, k, l, delta0, c0, delta90, c90))

    if not rows:
        raise ValueError(f"No data rows found in '{path}'.")
    return pd.DataFrame(
        rows,
        columns=["h", "k", "l", "delta_phi0", "C_phi0", "delta_phi90", "C_phi90"],
    )


def parse_project_table_multi_phi(path: str) -> tuple[pd.DataFrame, list[float]]:
    """
    Supports the extended table written by main.py:
      h k l  (delta/H, C)_phi1  (delta/H, C)_phi2  ...

    Returns:
      (df, phi_values)
    where df contains columns:
      h,k,l plus: delta_phi{phi}, C_phi{phi} for each phi.
    """
    header_phi: list[float] = []
    rows: list[list[float]] = []
    hkls: list[tuple[int, int, int]] = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            raw = line.strip()
            if not raw:
                continue

            if raw.startswith("#"):
                parts = raw.replace("#", "").split()
                header_phi = []
                for p in parts:
                    if p.startswith("C_eq_avg_phi"):
                        header_phi.append(float(p[len("C_eq_avg_phi"):]))
                continue

            parts = raw.split()
            if len(parts) < 3:
                continue

            h, k, l = map(int, parts[0:3])
            hkls.append((h, k, l))

            nums = list(map(float, parts[3:]))
            rows.append(nums)

    if not hkls:
        raise ValueError(f"No data rows found in '{path}'.")
    if not header_phi:
        raise ValueError(f"Could not parse phi columns from header in '{path}'.")

    expected = 2 * len(header_phi)
    for r in rows:
        if len(r) < expected:
            raise ValueError(f"Row has {len(r)} numeric fields, expected {expected}.")

    df = pd.DataFrame(hkls, columns=["h", "k", "l"])
    for i, phi in enumerate(header_phi):
        df[f"delta_phi{phi:g}"] = [r[2 * i + 0] for r in rows]
        df[f"C_phi{phi:g}"] = [r[2 * i + 1] for r in rows]

    return df, header_phi


# ============================
# Fitting
# ============================


def feature_vector_hexagonal_miller_scaled(h: int, k: int, l: int, cell: Cell) -> tuple[list[str], np.ndarray]:
    """
    Hexagonal (SG 168..194) TOPAS-style using MILLER indices (no direction cosines),
    with TOPAS normalization: (d(hkl)^4 / a^4).

    Cbar = (d^4/a^4) * [ E1*A^2 + 2*E2*l^2*A + E3*l^4 ]
    where A = h^2 + h*k + k^2  for gamma=120
          A = h^2 - h*k + k^2  for gamma=60
    """
    d = d_spacing(cell, h, k, l)
    scale = (d**4) / (float(cell.a)**4)

    h2, k2, l2 = h*h, k*k, l*l
    l4 = l2*l2

    # TOPAS uses + for 120°, - for 60°
    if _is_close(cell.gamma, 120.0):
        A = h2 + h*k + k2
    else:
        A = h2 - h*k + k2

    names = ["E1", "E2", "E3"]
    x = np.array([
        (A*A) * scale,            # E1
        (2.0*l2*A) * scale,       # E2
        (l4) * scale,             # E3
    ], dtype=float)
    return names, x



def feature_vector_monoclinic_miller_scaled(h: int, k: int, l: int, cell: Cell) -> tuple[list[str], np.ndarray]:
    """
    Monoclinic (SG 3..15, alpha=gamma=90) using MILLER indices (no direction cosines),
    scaled by TOPAS normalization: (d(hkl)^4 / a^4).

    Cbar = (d^4/a^4) * [E1 h^4 + E2 k^4 + E3 l^4
                       +2E4 h^2 l^2 +2E5 k^2 l^2 +2E6 h^2 k^2
                       +4E7 h^3 l +4E8 h l^3 +4E9 h k^2 l]
    """
    d = d_spacing(cell, h, k, l)
    scale = (d**4) / (float(cell.a)**4)

    h2, k2, l2 = h*h, k*k, l*l
    h3, l3 = h2*h, l2*l
    h4, k4, l4 = h2*h2, k2*k2, l2*l2

    names = [f"E{i}" for i in range(1, 10)]
    x = np.array([
        h4 * scale,                 # E1
        k4 * scale,                 # E2
        l4 * scale,                 # E3
        (2.0*h2*l2) * scale,        # E4
        (2.0*k2*l2) * scale,        # E5
        (2.0*h2*k2) * scale,        # E6
        (4.0*h3*l) * scale,         # E7
        (4.0*h*l3) * scale,         # E8
        (4.0*h*k2*l) * scale,       # E9
    ], dtype=float)
    return names, x



def fit_case_with_mode(
    df: pd.DataFrame,
    sg: int,
    cell: Cell,
    obs_col: str,
    mode: str,  # "topas" or "paper"
) -> Tuple[Dict[str, float], pd.DataFrame, Dict[str, float]]:

    y = df[obs_col].astype(float).to_numpy()
    reflections = list(zip(df["h"].astype(int), df["k"].astype(int), df["l"].astype(int)))

    A_rows: list[np.ndarray] = []
    term_names: list[str] = []

    for (h, k, l) in reflections:
        if mode == "paper":
            # Keep paper-special cases for tetragonal and cubic.
            if 75 <= sg <= 88:
                names_i, x_i = feature_vector_tetragonal_75_88_paper(h, k, l, cell)
            elif 89 <= sg <= 142:
                names_i, x_i = feature_vector_tetragonal_89_142_paper(h, k, l, cell)
            elif 195 <= sg <= 230:
                names_i, x_i = feature_vector_cubic_miller_paper(h, k, l, cell)
            else:
                # For monoclinic SG 3..15 with alpha=gamma=90, use Miller+scale (no direction cosines)
                if 3 <= sg <= 15 and _is_close(cell.alpha, 90.0) and _is_close(cell.gamma, 90.0):
                    names_i, x_i = feature_vector_monoclinic_miller_scaled(h, k, l, cell)
                else:
                    # For any other SG not covered by paper-special cases, fall back to TOPAS direction-cosines
                    H, K, L = HKL_direction_cosines(h, k, l, cell)
                    names_i, x_i = feature_vector(sg, H, K, L, cell)

        elif mode == "topas":
            # Miller-only + TOPAS normalization for monoclinic + hexagonal
            if 3 <= sg <= 15 and _is_close(cell.alpha, 90.0) and _is_close(cell.gamma, 90.0):
                names_i, x_i = feature_vector_monoclinic_miller_scaled(h, k, l, cell)
        
            elif 168 <= sg <= 194:
                names_i, x_i = feature_vector_hexagonal_miller_scaled(h, k, l, cell)
        
            else:
                H, K, L = HKL_direction_cosines(h, k, l, cell)
                names_i, x_i = feature_vector(sg, H, K, L, cell)



        else:
            raise ValueError("mode must be 'topas' or 'paper'")

        term_names = names_i
        A_rows.append(x_i)

    A = np.vstack(A_rows)

    coeffs, *_ = np.linalg.lstsq(A, y, rcond=None)
    y_calc = A @ coeffs
    resid = y - y_calc

    rmse = float(np.sqrt(np.mean(resid**2)))
    max_abs = float(np.max(np.abs(resid)))
    ss_res = float(np.sum(resid**2))
    ss_tot = float(np.sum((y - np.mean(y))**2))
    r2 = float(1.0 - ss_res / ss_tot) if ss_tot > 0 else float("nan")

    E_fit = {name: float(val) for name, val in zip(term_names, coeffs)}

    out = df[["h", "k", "l"]].copy()
    out.insert(
        3,
        "d_star",
        [1.0 / d_spacing(cell, int(h), int(k), int(l)) for (h, k, l) in reflections],
    )
    out["obs"] = y
    out["calc"] = y_calc
    out["resid"] = resid
    out["abs_resid"] = np.abs(resid)

    metrics = {
        "rmse": rmse,
        "max_abs_resid": max_abs,
        "r2": r2,
        "n": int(len(df)),
        "n_params": int(len(term_names)),
        "mode": mode,
    }
    return E_fit, out, metrics


def fit_case(
    df: pd.DataFrame,
    sg: int,
    cell: Cell,
    obs_col: str,
) -> Tuple[Dict[str, float], pd.DataFrame, Dict[str, float]]:
    """
    Single-mode fit used by run_fit_multi_phi().
    """
    y = df[obs_col].astype(float).to_numpy()
    reflections = list(zip(df["h"].astype(int), df["k"].astype(int), df["l"].astype(int)))

    A_rows: list[np.ndarray] = []
    term_names = required_terms_for_sg(sg, cell)

    for (h, k, l) in reflections:
        if 75 <= sg <= 88:
            names_i, x_i = feature_vector_tetragonal_75_88_paper(h, k, l, cell)
        elif 89 <= sg <= 142:
            names_i, x_i = feature_vector_tetragonal_89_142_paper(h, k, l, cell)
        elif 195 <= sg <= 230:
            names_i, x_i = feature_vector_cubic_miller_paper(h, k, l, cell)
        else:
            if 3 <= sg <= 15 and _is_close(cell.alpha, 90.0) and _is_close(cell.gamma, 90.0):
                names_i, x_i = feature_vector_monoclinic_miller_scaled(h, k, l, cell)
            elif 168 <= sg <= 194:
                names_i, x_i = feature_vector_hexagonal_miller_scaled(h, k, l, cell)
            else:
                H, K, L = HKL_direction_cosines(h, k, l, cell)
                names_i, x_i = feature_vector(sg, H, K, L, cell)

        term_names = names_i
        A_rows.append(x_i)

    A = np.vstack(A_rows)

    coeffs, *_ = np.linalg.lstsq(A, y, rcond=None)
    y_calc = A @ coeffs
    resid = y - y_calc

    rmse = float(np.sqrt(np.mean(resid**2)))
    max_abs = float(np.max(np.abs(resid)))
    ss_res = float(np.sum(resid**2))
    ss_tot = float(np.sum((y - np.mean(y))**2))
    r2 = float(1.0 - ss_res / ss_tot) if ss_tot > 0 else float("nan")

    E_fit = {name: float(val) for name, val in zip(term_names, coeffs)}

    out = df[["h", "k", "l"]].copy()
    out.insert(
        3,
        "d_star",
        [1.0 / d_spacing(cell, int(h), int(k), int(l)) for (h, k, l) in reflections],
    )
    out["obs"] = y
    out["calc"] = y_calc
    out["resid"] = resid
    out["abs_resid"] = np.abs(resid)

    metrics = {
        "rmse": rmse,
        "max_abs_resid": max_abs,
        "r2": r2,
        "n": int(len(df)),
        "n_params": int(len(term_names)),
    }
    return E_fit, out, metrics


# ============================
# Public API (no __main__)
# ============================

def run_fit(
    contrast_in_path: str | Path | None = None,
    input_table: str | Path | None = None,
    output_dir: str | Path = OUTPUT_DIR,
    out_prefix: str = OUT_PREFIX,
) -> tuple[
    dict[str, float], dict[str, float],   # E_screw_topas, metrics_screw_topas
    dict[str, float], dict[str, float],   # E_edge_topas,  metrics_edge_topas
    dict[str, float], dict[str, float],   # E_screw_paper, metrics_screw_paper
    dict[str, float], dict[str, float],   # E_edge_paper,  metrics_edge_paper
    Path, Path,                           # csv_screw_topas, csv_edge_topas
    Path, Path                            # csv_screw_paper, csv_edge_paper
]:
    """
    Runs invariant fits in two modes:

      1) TOPAS: direction-cosines feature vector (your original macro logic)
      2) PAPER: (kept only for tetragonal + cubic). For all other SG, falls back to TOPAS.

    NOTE:
      Monoclinic PAPER normalization removed.
    """
    # Load contrast_factors.in
    if contrast_in_path is None:
        contrast_in_path = _resolve_contrast_input_path()
    else:
        contrast_in_path = Path(contrast_in_path).resolve()

    with Path(contrast_in_path).open("r", encoding="utf-8") as f:
        contrast_in = json.load(f)

    sg_file = int(
        contrast_in.get("space_group")
        or _default_sg_for_lattice(str(contrast_in["cell"]["lattice"]))
    )
    cell_file = _load_cell_from_contrast_in(contrast_in)

    sg = FORCE_SG if FORCE_SG is not None else sg_file
    if FORCE_CELL is not None:
        a, b, c, al, be, ga = FORCE_CELL
        cell = Cell(a=a, b=b, c=c, alpha=al, beta=be, gamma=ga)
    else:
        cell = cell_file

    # Resolve input table path
    if input_table is None:
        if FORCE_INPUT_TABLE:
            in_table = Path(FORCE_INPUT_TABLE).resolve()
        else:
            in_table = _output_table_path_from_contrast_in(Path(contrast_in_path))
    else:
        in_table = Path(input_table).resolve()

    if not in_table.exists():
        raise FileNotFoundError(
            f"Contrast-factor table not found: {in_table}\n"
            "Run main.py first (to generate the table) or set FORCE_INPUT_TABLE."
        )

    df = parse_project_table(str(in_table))

    # Output paths
    os.makedirs(str(output_dir), exist_ok=True)
    base = (Path(output_dir) / out_prefix).resolve()

    # TOPAS fits
    E_screw_topas, tab_screw_topas, met_screw_topas = fit_case_with_mode(
        df, sg, cell, obs_col="C_phi0", mode="topas"
    )
    E_edge_topas, tab_edge_topas, met_edge_topas = fit_case_with_mode(
        df, sg, cell, obs_col="C_phi90", mode="topas"
    )

    # PAPER fits (tetragonal/cubic only; others fallback to TOPAS)
    E_screw_paper, tab_screw_paper, met_screw_paper = fit_case_with_mode(
        df, sg, cell, obs_col="C_phi0", mode="paper"
    )
    E_edge_paper, tab_edge_paper, met_edge_paper = fit_case_with_mode(
        df, sg, cell, obs_col="C_phi90", mode="paper"
    )

    # Write CSVs
    csv_screw_topas = Path(f"{base}_comparison_screw_TOPAS.csv").resolve()
    csv_edge_topas  = Path(f"{base}_comparison_edge_TOPAS.csv").resolve()
    csv_screw_paper = Path(f"{base}_comparison_screw_PAPER.csv").resolve()
    csv_edge_paper  = Path(f"{base}_comparison_edge_PAPER.csv").resolve()

    tab_screw_topas.to_csv(csv_screw_topas, index=False)
    tab_edge_topas.to_csv(csv_edge_topas, index=False)
    tab_screw_paper.to_csv(csv_screw_paper, index=False)
    tab_edge_paper.to_csv(csv_edge_paper, index=False)

    return (
        E_screw_topas, met_screw_topas,
        E_edge_topas,  met_edge_topas,
        E_screw_paper, met_screw_paper,
        E_edge_paper,  met_edge_paper,
        csv_screw_topas, csv_edge_topas,
        csv_screw_paper, csv_edge_paper
    )


def run_fit_multi_phi(
    contrast_in_path: str | Path | None = None,
    input_table: str | Path | None = None,
    output_dir: str | Path = OUTPUT_DIR,
    out_prefix: str = OUT_PREFIX,
) -> tuple[dict[float, dict[str, float]], dict[float, dict[str, float]], dict[float, Path]]:
    """
    Runs invariant fit for EACH phi present in the table.
    Returns:
      (E_by_phi, metrics_by_phi, csv_by_phi)

    NOTE:
      This function uses fit_case(), which:
        - keeps tetragonal/cubic paper feature vectors
        - falls back to TOPAS direction-cosines otherwise
        - NO monoclinic paper normalization.
    """
    if contrast_in_path is None:
        contrast_in_path = _resolve_contrast_input_path()
    else:
        contrast_in_path = Path(contrast_in_path).resolve()

    with Path(contrast_in_path).open("r", encoding="utf-8") as f:
        contrast_in = json.load(f)

    sg_file = int(
        contrast_in.get("space_group")
        or _default_sg_for_lattice(str(contrast_in["cell"]["lattice"]))
    )
    cell_file = _load_cell_from_contrast_in(contrast_in)

    sg = FORCE_SG if FORCE_SG is not None else sg_file
    cell = Cell(*FORCE_CELL) if FORCE_CELL is not None else cell_file  # type: ignore[arg-type]

    if input_table is None:
        if FORCE_INPUT_TABLE:
            in_table = Path(FORCE_INPUT_TABLE).resolve()
        else:
            in_table = _output_table_path_from_contrast_in(Path(contrast_in_path))
    else:
        in_table = Path(input_table).resolve()

    if not in_table.exists():
        raise FileNotFoundError(f"Contrast-factor table not found: {in_table}")

    df, phi_values = parse_project_table_multi_phi(str(in_table))

    os.makedirs(str(output_dir), exist_ok=True)
    base = Path(output_dir) / out_prefix

    E_by_phi: dict[float, dict[str, float]] = {}
    metrics_by_phi: dict[float, dict[str, float]] = {}
    csv_by_phi: dict[float, Path] = {}

    for phi in phi_values:
        col = f"C_phi{phi:g}"
        E_fit, tab, met = fit_case(df, sg, cell, obs_col=col)

        csv_path = Path(f"{base}_comparison_phi{phi:g}.csv").resolve()
        tab.to_csv(csv_path, index=False)

        E_by_phi[phi] = E_fit
        metrics_by_phi[phi] = met
        csv_by_phi[phi] = csv_path

    return E_by_phi, metrics_by_phi, csv_by_phi


def run_fit_multi_phi_dual(
    contrast_in_path: str | Path | None = None,
    input_table: str | Path | None = None,
    output_dir: str | Path = OUTPUT_DIR,
    out_prefix: str = OUT_PREFIX,
) -> tuple[
    dict[float, dict[str, float]], dict[float, dict[str, float]], dict[float, Path],   # TOPAS: E, metrics, csv
    dict[float, dict[str, float]], dict[float, dict[str, float]], dict[float, Path],   # PAPER: E, metrics, csv
]:
    """
    Runs invariant fit for EACH phi present in the table, in TWO modes:
      - TOPAS (direction cosines)
      - PAPER (tetragonal/cubic paper forms; others fallback to TOPAS)

    NOTE:
      Monoclinic PAPER normalization removed.
    """
    if contrast_in_path is None:
        contrast_in_path = _resolve_contrast_input_path()
    else:
        contrast_in_path = Path(contrast_in_path).resolve()

    with Path(contrast_in_path).open("r", encoding="utf-8") as f:
        contrast_in = json.load(f)

    sg_file = int(
        contrast_in.get("space_group")
        or _default_sg_for_lattice(str(contrast_in["cell"]["lattice"]))
    )
    cell_file = _load_cell_from_contrast_in(contrast_in)

    sg = FORCE_SG if FORCE_SG is not None else sg_file
    if FORCE_CELL is not None:
        a, b, c, al, be, ga = FORCE_CELL
        cell = Cell(a=a, b=b, c=c, alpha=al, beta=be, gamma=ga)
    else:
        cell = cell_file

    # input table
    if input_table is None:
        if FORCE_INPUT_TABLE:
            in_table = Path(FORCE_INPUT_TABLE).resolve()
        else:
            in_table = _output_table_path_from_contrast_in(Path(contrast_in_path))
    else:
        in_table = Path(input_table).resolve()

    if not in_table.exists():
        raise FileNotFoundError(f"Contrast-factor table not found: {in_table}")

    df, phi_values = parse_project_table_multi_phi(str(in_table))

    os.makedirs(str(output_dir), exist_ok=True)
    base = (Path(output_dir) / out_prefix).resolve()

    # TOPAS
    E_topas_by_phi: dict[float, dict[str, float]] = {}
    metrics_topas_by_phi: dict[float, dict[str, float]] = {}
    csv_topas_by_phi: dict[float, Path] = {}

    # PAPER
    E_paper_by_phi: dict[float, dict[str, float]] = {}
    metrics_paper_by_phi: dict[float, dict[str, float]] = {}
    csv_paper_by_phi: dict[float, Path] = {}

    for phi in phi_values:
        col = f"C_phi{phi:g}"

        # TOPAS
        E_t, tab_t, met_t = fit_case_with_mode(df, sg, cell, obs_col=col, mode="topas")
        csv_t = Path(f"{base}_comparison_phi{phi:g}_TOPAS.csv").resolve()
        tab_t.to_csv(csv_t, index=False)

        E_topas_by_phi[phi] = E_t
        metrics_topas_by_phi[phi] = met_t
        csv_topas_by_phi[phi] = csv_t

        # PAPER (tetragonal/cubic forms only; others fallback to TOPAS)
        E_p, tab_p, met_p = fit_case_with_mode(df, sg, cell, obs_col=col, mode="paper")
        csv_p = Path(f"{base}_comparison_phi{phi:g}_PAPER.csv").resolve()
        tab_p.to_csv(csv_p, index=False)

        E_paper_by_phi[phi] = E_p
        metrics_paper_by_phi[phi] = met_p
        csv_paper_by_phi[phi] = csv_p

    return (
        E_topas_by_phi, metrics_topas_by_phi, csv_topas_by_phi,
        E_paper_by_phi, metrics_paper_by_phi, csv_paper_by_phi,
    )


def _resolve_contrast_input_path() -> Path:
    here = Path(__file__).resolve().parent
    for p in (
        here / ".." / "contrast_factors.in",
        here / ".." / ".." / "contrast_factors.in",
        Path("Contrast_Factor/contrast_factors.in").resolve(),
        Path("contrast_factors.in").resolve(),
    ):
        p = p.resolve()
        if p.exists():
            return p
    raise FileNotFoundError(
        "Unable to find 'contrast_factors.in'. Make sure it exists and the working directory is correct."
    )
