from __future__ import annotations

import math
from typing import List
import itertools
import numpy as np

from .models import ContrastFactorInput
from .geometry import build_slip_frame

# ---------- Elementary rotations ----------

def _rot_x(theta: float) -> np.ndarray:
    c, s = math.cos(theta), math.sin(theta)
    return np.array([[1.0, 0.0, 0.0],
                     [0.0, c,   -s ],
                     [0.0, s,    c ]], dtype=float)

def _rot_y(theta: float) -> np.ndarray:
    c, s = math.cos(theta), math.sin(theta)
    return np.array([[  c, 0.0,  s ],
                     [0.0, 1.0, 0.0],
                     [ -s, 0.0,  c ]], dtype=float)

def _rot_z(theta: float) -> np.ndarray:
    c, s = math.cos(theta), math.sin(theta)
    return np.array([[ c,  -s, 0.0],
                     [ s,   c, 0.0],
                     [0.0, 0.0, 1.0]], dtype=float)

def _rod(axis: np.ndarray, theta: float) -> np.ndarray:
    """
    Rodrigues rotation about an arbitrary axis.
    The axis is given in the orthonormal E frame.
    """
    axis = np.asarray(axis, dtype=float)
    axis = axis / np.linalg.norm(axis)
    x, y, z = axis
    c, s = math.cos(theta), math.sin(theta)
    C = 1.0 - c
    return np.array([
        [c + x*x*C,   x*y*C - z*s, x*z*C + y*s],
        [y*x*C + z*s, c + y*y*C,   y*z*C - x*s],
        [z*x*C - y*s, z*y*C + x*s, c + z*z*C  ],
    ], dtype=float)

# ---------- Generic finite group builder ----------

def _generate_group(generators: List[np.ndarray],
                    include_improper: bool) -> List[np.ndarray]:
    """
    Build the (finite) point group generated by the given proper rotations.
    If include_improper is True, inversion (-I) is also used as a generator.
    All matrices are expressed in the orthonormal E frame used everywhere
    in this library.
    """
    tol = 1e-12
    gens = [np.asarray(G, dtype=float) for G in generators]

    if include_improper:
        inv = -np.eye(3, dtype=float)
        gens.append(inv)

    group: List[np.ndarray] = []
    stack: List[np.ndarray] = []

    I = np.eye(3, dtype=float)
    group.append(I)
    stack.append(I)

    def _contains(mat: np.ndarray) -> bool:
        return any(np.allclose(mat, G, atol=tol) for G in group)

    while stack:
        g = stack.pop(0)
        for gen in gens:
            h = gen @ g
            # Clean small numerical noise close to {-1,0,1}
            h_clean = h.copy()
            h_clean[np.abs(h_clean) < tol] = 0.0
            # Snap to +/-1 if close to 1
            for i in range(3):
                for j in range(3):
                    v = h_clean[i, j]
                    if abs(abs(v) - 1.0) < 1e-10:
                        h_clean[i, j] = math.copysign(1.0, v)
            if not _contains(h_clean):
                group.append(h_clean)
                stack.append(h_clean)

    return group

# ---------- Explicit Laue-class point groups ----------

def _cubic_m3m_rotations(include_improper: bool) -> list[np.ndarray]:
    mats = []
    for perm in itertools.permutations([0,1,2], 3):
        P = np.zeros((3,3), float)
        for i, j in enumerate(perm):
            P[i, j] = 1.0
        for signs in itertools.product([-1.0, 1.0], repeat=3):
            S = np.diag(signs)
            R = S @ P
            det = round(np.linalg.det(R))
            # proper subgroup: det=+1
            if det == 1:
                mats.append(R)

  

    if include_improper:
        inv = -np.eye(3)
        improper = [inv @ R for R in mats]  # det=-1 partners
        mats = mats + improper

    return mats

def _hex_6mmm_rotations(include_improper: bool) -> List[np.ndarray]:
    """
    6/mmm Laue group (D6h) with the 6-fold axis along z.
    """
    C6 = _rot_z(math.pi/3.0)   # 60°
    C2x = _rot_x(math.pi)      # 2-fold about x in the basal plane
    return _generate_group([C6, C2x], include_improper)

def _tetragonal_4mmm_rotations(include_improper: bool) -> List[np.ndarray]:
    """
    4/mmm Laue group (D4h) with the 4-fold axis along z.
    """
    C4 = _rot_z(math.pi/2.0)   # 90°
    C2x = _rot_x(math.pi)      # 2-fold about x
    return _generate_group([C4, C2x], include_improper)

def _tetragonal_4m_rotations(include_improper: bool) -> List[np.ndarray]:
    """
    Point group 4/m (C4h) as 3x3 orthogonal matrices.
    Proper part: rotations about z by 0, 90, 180, 270 degrees (4 ops).
    Improper part (if requested): multiply each proper op by inversion (-I) -> det = -1 (4 more).
    Total: 4 (proper) or 8 (with improper).
    """
    R0 = np.array([[ 1.,  0., 0.],
                   [ 0.,  1., 0.],
                   [ 0.,  0., 1.]])

    R90 = np.array([[ 0., -1., 0.],
                    [ 1.,  0., 0.],
                    [ 0.,  0., 1.]])

    R180 = np.array([[-1.,  0., 0.],
                     [ 0., -1., 0.],
                     [ 0.,  0., 1.]])

    R270 = np.array([[ 0.,  1., 0.],
                     [-1.,  0., 0.],
                     [ 0.,  0., 1.]])

    proper = [R0, R90, R180, R270]

    if not include_improper:
        return proper

    inv = -np.eye(3)
    improper = [inv @ R for R in proper]
    return proper + improper


def _trigonal_3m_rotations(include_improper: bool) -> List[np.ndarray]:
    """
    -3m Laue group (D3d) with the 3-fold axis along z.
    """
    C3 = _rot_z(2.0*math.pi/3.0)  # 120°
    C2x = _rot_x(math.pi)         # 2-fold about x
    return _generate_group([C3, C2x], include_improper)

def _orthorhombic_mmm_rotations(include_improper: bool) -> List[np.ndarray]:
    """
    mmm Laue group (D2h) with the three mutually perpendicular 2-fold axes
    along x, y, z.
    """
    C2x = _rot_x(math.pi)
    C2y = _rot_y(math.pi)
    return _generate_group([C2x, C2y], include_improper)

def _monoclinic_2m_rotations(include_improper: bool) -> List[np.ndarray]:
    """
    2/m Laue group with the unique axis b taken along y.
    The rotational subgroup has E and a 2-fold about y.
    """
    C2y = _rot_y(math.pi)
    return _generate_group([C2y], include_improper)

def _triclinic_1bar_rotations(include_improper: bool) -> List[np.ndarray]:
    """
    -1 Laue group (Ci). Only identity and (optionally) inversion.
    """
    if include_improper:
        return [np.eye(3, dtype=float), -np.eye(3, dtype=float)]
    else:
        return [np.eye(3, dtype=float)]

# ---------- Public API ----------

def build_point_group_rotations_from_laue(
    cf_input: ContrastFactorInput,
    include_improper: bool = False
) -> List[np.ndarray]:
    """
    Return the list of 3x3 orthogonal matrices representing the point-group
    operations of the Laue class associated with this material.
    The matrices act on vectors expressed in the orthonormal E frame.

    We infer the Laue class from the lattice type, in the same way as the
    original Mathematica code used the crystal class to build OperatorInE.
    """
    lat = (cf_input.cell.lattice or "").lower()

    if lat == "cubic":
        return _cubic_m3m_rotations(include_improper)
    if lat == "hexagonal":
        return _hex_6mmm_rotations(include_improper)
    if lat == "tetragonal":
        sg = int(getattr(cf_input, "space_group", 0) or 0)

        # TOPAS rule you quoted:
        # 75..88  -> 4/m   (needs E5)
        # 89..142 -> 4/mmm (E5 must vanish by symmetry)
        if 75 <= sg <= 88:
            return _tetragonal_4m_rotations(include_improper)
        else:
            return _tetragonal_4mmm_rotations(include_improper)
    if lat == "trigonal":
        return _trigonal_3m_rotations(include_improper)
    if lat == "orthorhombic":
        return _orthorhombic_mmm_rotations(include_improper)
    if lat == "monoclinic":
        return _monoclinic_2m_rotations(include_improper)
    if lat == "triclinic":
        return _triclinic_1bar_rotations(include_improper)

    # Fallback: no symmetry information, only identity.
    return [np.eye(3, dtype=float)]

# ---------- Slip-frame equivalence ----------

def _mathematica_delete_rule_rows(x_rows: np.ndarray, k_rows: np.ndarray, atol: float = 1e-12) -> bool:
    # x == k
    if np.allclose(x_rows, k_rows, atol=atol):
        return True

    k1, k2, k3 = k_rows[0], k_rows[1], k_rows[2]   # ROWS
    x1 = x_rows[0]

    # x[[1]] == -k[[1]]  (ONLY row 1)
    if np.allclose(x1, -k1, atol=atol):
        return True

    # x == {k1,-k2,k3}, {-k1,k2,k3}, {k1,k2,-k3}, {k1,-k2,-k3}, {-k1,-k2,k3}
    if np.allclose(x_rows, np.vstack(( k1, -k2,  k3)), atol=atol):
        return True
    if np.allclose(x_rows, np.vstack((-k1,  k2,  k3)), atol=atol):
        return True
    if np.allclose(x_rows, np.vstack(( k1,  k2, -k3)), atol=atol):
        return True
    if np.allclose(x_rows, np.vstack(( k1, -k2, -k3)), atol=atol):
        return True
    if np.allclose(x_rows, np.vstack((-k1, -k2,  k3)), atol=atol):
        return True

    return False


def _frames_equivalent(P: np.ndarray, Q: np.ndarray, atol: float = 1e-12) -> bool:
    """
    Match Mathematica EquivalentSlipSystem pruning (DeleteCases):
    treat frames as equivalent only under these sign flips of (e1,e2,e3):

      (+,+,+), (-,+,+), (+,-,+), (+,+,-), (+,-,-), (-,-,+)

    i.e. DO NOT identify (-,+,-) or (-,-,-) as equivalent.
    """
    P = np.asarray(P, dtype=float)
    Q = np.asarray(Q, dtype=float)

    allowed = [
        (+1, +1, +1),
        (-1, +1, +1),
        (+1, -1, +1),
        (+1, +1, -1),
        (+1, -1, -1),
        (-1, -1, +1),
    ]

    for s1, s2, s3 in allowed:
        D = np.diag([s1, s2, s3])
        if np.allclose(P @ D, Q, atol=atol):
            return True

    return False





def equivalent_slip_frames(cf_input, include_improper: bool = False, debug: bool = False):
    e1, e2, e3 = build_slip_frame(cf_input)
    F0 = np.vstack((e1, e2, e3))  # ROWS (e1,e2,e3)

    R_list = build_point_group_rotations_from_laue(cf_input, include_improper=include_improper)

    # Apply R to each ROW vector, exactly like Mathematica cand = {R.e1,R.e2,R.e3}
    candidates = [np.vstack((R @ F0[0], R @ F0[1], R @ F0[2])) for R in R_list]

    uniq = []
    atol = 1e-12

    while candidates:
        k = candidates.pop(0)
        uniq.append(k)
        candidates = [x for x in candidates if not _mathematica_delete_rule_rows(x, k, atol=atol)]

    if debug:
        print("N rotations =", len(R_list))
        print("N unique frames =", len(uniq))

    return uniq

