# cfactor/wppm_macro.py
from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional, Tuple, List

E_KEYS = [f"E{i}" for i in range(1, 16)]


def _get_phi_coeffs(E_by_phi: Dict[float, Dict[str, float]], phi: float) -> Dict[str, float]:
    """
    Return {E1..E15} dict for a given phi (e.g. 0 screw, 90 edge).
    Missing Ei are set to 0.0 for robustness.
    """
    if phi not in E_by_phi:
        raise KeyError(f"phi={phi} not found in fitted results. Available: {sorted(E_by_phi.keys())}")

    coeffs = dict(E_by_phi[phi])
    for k in E_KEYS:
        coeffs.setdefault(k, 0.0)
    return coeffs


def _is_zero(x: float, tol: float) -> bool:
    return abs(float(x)) <= tol


def _last_nonzero_index(E_edge: Dict[str, float], E_screw: Dict[str, float], tol: float) -> int:
    """
    Returns the largest i (1..15) such that either Ei_edge or Ei_screw is non-zero.
    Returns 0 if all are zero.
    """
    last = 0
    for i in range(1, 16):
        k = f"E{i}"
        if (not _is_zero(E_edge.get(k, 0.0), tol)) or (not _is_zero(E_screw.get(k, 0.0), tol)):
            last = i
    return last


def write_wppm_inp_from_fit(
    out_path: Path,
    *,
    E_by_phi: Dict[float, Dict[str, float]],
    wsg: int,
    burgers_uvw: Optional[Tuple[int, int, int]] = None,
    burgers_expr: Optional[str] = None,
    phi_screw: float = 0.0,
    phi_edge: float = 90.0,
    rho_init: float = 3.16531647e-4,
    rho_min: float = 0.0,
    rho_max: float = 0.1,
    re_expr: str = "Diameter",
    fE_init: float = 0.5,
    macro_name: str = "WPPM_Strain_InvariantWilkens",
    include_macro_file: str | None = None,

    # extras
    add_size_dist_block: bool = True,
    example_hkl: Tuple[int, int, int] = (1, 1, 0),
    warren_filename: str = "warren_plot.txt",
    warren_Lstep: float = 0.5,

    # NEW: tolerance to decide whether an Ei is treated as zero
    zero_tol: float = 1e-12,
) -> None:
    """
    Generate a TOPAS-ready input block (wppm.inp) that:
      - defines rho, re, fE
      - defines ONLY non-zero Ei_edge/Ei_screw (within zero_tol)
      - defines mixed Ei only for those non-zero coefficients
      - calls WPPM_Strain_InvariantWilkens with a shortened Ei list (up to last non-zero Ei)
      - calls Out_Warren_Plot with the full Ei list, but inserts literal 0 for zero Ei
    """
    E_screw = _get_phi_coeffs(E_by_phi, phi_screw)
    E_edge = _get_phi_coeffs(E_by_phi, phi_edge)

    last_i = _last_nonzero_index(E_edge, E_screw, zero_tol)

    # If everything is (numerically) zero, still call with at least E1 so TOPAS doesn't choke
    # (This should not happen in normal use, but keeps the file syntactically consistent.)
    if last_i == 0:
        last_i = 1

    used_E_keys: List[str] = [f"E{i}" for i in range(1, last_i + 1)]

    lines: list[str] = []
    lines.append("' =====================================================================")
    lines.append("'  Auto-generated by DISCO (cfactor.wppm_macro)")
    lines.append(f"'  screw phi={phi_screw:g} deg, edge phi={phi_edge:g} deg")
    lines.append(f"'  Ei printed up to E{last_i} (|Ei| <= {zero_tol:g} treated as zero)")
    lines.append("' =====================================================================")
    lines.append("")

    # include
    if include_macro_file:
        lines.append(f"#include {include_macro_file}")
        lines.append("")

    # Optional crystallite-size distribution block (lognormal spheres)
    if add_size_dist_block:
        lines.append("' --- Crystallite size distribution (lognormal spheres) ---")
        lines.append("prm !mu  2.7_0.1 min .1 max = Min(2 Val + .02, 5); val_on_continue = Rand(1, 3);")
        lines.append("prm !si  0.25_0.03 min .01 max = Min(2 Val + .01, 1); val_on_continue = Rand(.1, 1);")
        lines.append("WPPM_Sphere_LogNormDIST(, mu, , si)")
        lines.append("prm !Diameter = Exp(mu+si^2/2);")
        lines.append("prm !StanDev  = (Exp(2*mu+si^2)*(Exp(si^2)-1))^(1/2);")
        lines.append("prm !LSur     = (2/3)*Exp(mu+2.5*si^2);")
        lines.append("prm !LVol     = (3/4)*Exp(mu+3.5*si^2);")
        lines.append("prm !Lambda   = Exp(mu+3.5*si^2);")
        lines.append("")

    # refinables
    lines.append(f"prm rho  {rho_init:.12g} min {rho_min:g} max {rho_max:g}")
    lines.append(f"prm re   ={re_expr}; min 0")
    lines.append(f"prm fE   {fE_init:.6g} min 0 max 1")
    lines.append("")

    # burgers
    if burgers_expr is not None and str(burgers_expr).strip():
        lines.append("' Burgers vector magnitude (user expression)")
        lines.append(f"prm !burgers = {burgers_expr};")
        lines.append("")
    else:
        if burgers_uvw is None:
            raise ValueError(
                "Either burgers_expr must be provided OR burgers_uvw must be provided "
                "to compute burgers via the cell metric."
            )
        u_val, v_val, w_val = burgers_uvw

        lines.append("' Burgers vector magnitude from cell metric (sf is a user-editable scale factor)")
        lines.append(f"prm !u  {int(u_val)}    ' Burgers direction component u")
        lines.append(f"prm !v  {int(v_val)}    ' Burgers direction component v")
        lines.append(f"prm !w  {int(w_val)}    ' Burgers direction component w")
        lines.append("prm !sf 1        ' scale factor (edit if needed, e.g. 0.5)")
        lines.append("")
        lines.append("prm !burgers = sf*Sqrt(")
        lines.append("    (u*u)*(Get(a)^2) + (v*v)*(Get(b)^2) + (w*w)*(Get(c)^2)")
        lines.append("  + 2*u*v*Get(a)*Get(b)*Cos(Get(ga))")
        lines.append("  + 2*u*w*Get(a)*Get(c)*Cos(Get(be))")
        lines.append("  + 2*v*w*Get(b)*Get(c)*Cos(Get(al))")
        lines.append(");")
        lines.append("")

    # fixed edge/screw coefficients (ONLY up to last_i, and ONLY if not both ~0)
    lines.append("' --- DISCO fitted contrast-factor coefficients (pure numbers) ---")
    for k in used_E_keys:
        ve = float(E_edge.get(k, 0.0))
        vs = float(E_screw.get(k, 0.0))
        if _is_zero(ve, zero_tol) and _is_zero(vs, zero_tol):
            continue  # do not declare all-zero coefficient pairs
        lines.append(f"prm !{k}_edge  {ve: .12g}")
        lines.append(f"prm !{k}_screw {vs: .12g}")
    lines.append("")

    # mixed (ONLY for coefficients that were declared above)
    lines.append("' --- Mixed coefficients using fE ---")
    for k in used_E_keys:
        ve = float(E_edge.get(k, 0.0))
        vs = float(E_screw.get(k, 0.0))
        if _is_zero(ve, zero_tol) and _is_zero(vs, zero_tol):
            continue
        lines.append(f"prm {k} = {k}_edge*fE + {k}_screw*(1-fE);")
    lines.append("")

    # WPPM macro call: pass only E1..E_last_i, but replace missing/zero with literal 0 if needed
    # (If a coefficient was not declared because it is zero, we pass 0 here.)
    wppm_args: List[str] = []
    for k in used_E_keys:
        ve = float(E_edge.get(k, 0.0))
        vs = float(E_screw.get(k, 0.0))
        if _is_zero(ve, zero_tol) and _is_zero(vs, zero_tol):
            wppm_args.append("0")
        else:
            wppm_args.append(k)

    lines.append(
        f"{macro_name}( , rho, , re, burgers, {int(wsg)}, " + ", ".join(wppm_args) + ")"
    )
    lines.append("")

    # Warren plot (full form; use 0 literals for zero coefficients)
    h, k, l = (int(example_hkl[0]), int(example_hkl[1]), int(example_hkl[2]))
    warren_E_args: List[str] = []
    for kk in E_KEYS:
        ve = float(E_edge.get(kk, 0.0))
        vs = float(E_screw.get(kk, 0.0))
        warren_E_args.append("0" if (_is_zero(ve, zero_tol) and _is_zero(vs, zero_tol)) else kk)

    lines.append("' --- Warren plot output (example hkl; edit as needed) ---")
    lines.append(
        "'Out_Warren_Plot("
        f"\"{warren_filename}\", {warren_Lstep:g}, {h}, {k}, {l}, "
        f"rho, burgers, re, {int(wsg)}, "
        + ", ".join(warren_E_args)
        + ") ' This command works only in TOPAS 8"
    )
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
